### PR TITLE
Fix issue #8

### PR DESCRIPTION
**Pull request by MrSpoocy**
With this fix, you can use `tag="div"`, `tag={<WhatEver />} ` or `tag={ variable }`

### CODE REVIEW

**Comment by TheSharpieOne** [comment]
This doesn't necessarily fix the issue. Passing `ref` to another Component (which doesn't use `forwardRef` will still result in a ref to the component and not a DOM element and we need a DOM element to get the bounding box.

Also, this introduces a dependency on a newer version of react (missing from the PR changeset)

I made #27 which should address the issue.

**Comment by MrSpoocy** [comment]
can you tell me which method has to high dependency, maybe you make new PR with support old version. I have try to figure out on https://github.com/facebook/react/blob/master/CHANGELOG.md

**Comment by TheSharpieOne** [comment]
It's the use of Fragments.

With the change I made, you can set the tag like `tag="main"` or `tag={WhatEver}`, you just can't do `tag={<WhatEver />}`. I don't really see a reason to do that last one. You can just do `tag={WhatEver}` and pass additional props to `BlockUi` which will be passed to `WhatEver` when it is rendered.

**Comment by MrSpoocy** [comment]
Hm, i have try follow snipped

`let row = <Row />;
         return (
            <BlockUi tag={row} blocking={this.state.blocking} {...other}>
                <Col>{username}</Col>
            </BlockUi>
        );`

Row & Col  from react-bootstrap. This was the reason why it was a problem to create a div around the row. And i have try to use the Row instand of the div. But i get this error ...

> Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
> Check the render method of `BlockUi`.

**Comment by TheSharpieOne** [comment]
Separate issue, we need to modify the propTypes to allow for what `forwardRef` returns (it's an object, not a function or a string)
That should just be a warning and can be ignored for now. I will modify the propTypes to account for `forwardRef` components.

**Pull request closed without merging**
